# Generated by Django 2.2.5 on 2021-07-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_post_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
