# Generated by Django 2.2.5 on 2021-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_last_post_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_post_seen',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_post_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
