# Generated by Django 2.2.5 on 2021-08-23 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20210801_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_post_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='DailyWaiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
