# Generated by Django 2.2.5 on 2021-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_dailywaiter_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywaiter',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
