# Generated by Django 2.2.5 on 2021-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210824_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_boxes',
            field=models.BooleanField(default=True),
        ),
    ]
