# Generated by Django 2.2.5 on 2021-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(help_text='Ára forintban')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('állandó', 'állandó'), ('napi menü', 'napi menü'), ('napi táblás', 'napi táblás'), ('egyéb', 'egyéb')], max_length=1)),
                ('boxes', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='1', max_length=1)),
            ],
        ),
    ]
