# Generated by Django 2.2.5 on 2021-06-30 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20210610_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='boxes',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='1', help_text='Szükséges dobozok száma', max_length=1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Csak a napi ajánlatoknál fontos!'),
        ),
    ]
