# Generated by Django 2.2.5 on 2021-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20210630_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
