# Generated by Django 2.2.5 on 2021-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Csak a napi menüknél használatos!', max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(help_text="Fogás neve. Napi menü estén 'Napi menü 1' vagy 'Napi menü 2'", max_length=100),
        ),
    ]
