# Generated by Django 2.2.5 on 2021-07-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
