# Generated by Django 2.2.5 on 2021-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_blogger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_part_date', '-publish_part_time', '-updated', '-timestamp']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_part_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_part_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
