# Generated by Django 2.2.5 on 2021-08-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210731_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_part_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_part_time',
        ),
    ]
